### ISSUE TITLE
can not run on Android devices

### ISSUE THREAD

**Issue by pansong291** [DexPatcher/dex2jar#2]
there are logs :
```
java.io.IOException: cant find zipfs support
	at com.googlecode.d2j.dex.Dex2jar.createZip(Dex2jar.java:294)
	at com.googlecode.d2j.dex.Dex2jar.to(Dex2jar.java:274)
	at com.googlecode.dex2jar.tools.Dex2jarCmd.doCommandLine(Dex2jarCmd.java:107)
	at com.googlecode.dex2jar.tools.BaseCmd.doMain(BaseCmd.java:290)
	at com.googlecode.dex2jar.tools.Dex2jarCmd.main(Dex2jarCmd.java:33)
```

**Comment by Lanchon** [comment]
that is correct. maybe ask dex2jar to output class files in a directory tree (was that possible at all?), or you might have success with older builds of dex2jar (version 1.x?).

**Comment by pansong291** [comment]
I have success with older builds of dex2jar (version 0.0.9.15).
Anyway, thank you for your response.
